title: AmanithSVG, a software library for reading and rendering SVG files
description: Standalone library for reading and rendering SVG files
description2:
url: https://www.amanithsvg.com
enforce_ssl: www.amanithsvg.com
google_analytics: UA-92998226-1
copyright: (C) 2018 Mazatech, Srl
vatid: VAT ID IT03498460405
rights: All rights reserved
product_name: AmanithSVG
company_email: "info@mazatech.com"
facebook_username: "mazatechsrl"
twitter_username: "Mazatech1"
github_username: "Mazatech"
collections:
  docs:
    output: true
assets:
  sources:
    - _assets
    - _assets/fonts
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
sass:
  sass_dir: _includes
  style: compressed
compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
plugins: 
  - jekyll-sitemap